version: '3.1'

services:
  api:
    build: ./.devcontainer/Dockerfile
    image: api:latest
    container_name: api
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
#      - "80"
      - "443"
    ports:
      - 80:80
    networks:
      - api_network
    depends_on:
      - adm_db

  adm_db:
    image: "postgres:latest"
    container_name: adm_db
    restart: always
    #expose:
     # - "5432"
    ports:
        - 5432:5432
    networks:
      - api_network
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  #proxy:
  #  build: ./nginx
  #  container_name: nginx
  #  ports:
  #   -  "80:80"
  #   #-  "443:443"
  #   - "1883:1883"
  #  networks:
  #    - web_api_network 
  #  depends_on:
  #    - webapi
  #    - dashboard

volumes:
  postgres:

networks:
  api_network: